from enum import Enum

class ResponseSignal(Enum):
    FILE_UPLOAD_FALIED = "FILE_FAILED"
    FILE_VALIDATE_SUCCESS = "FILE_VALIDATE_SUCCESS"
    FILE_UPLOAD_NOT_ALLOWED = "FILE_NOT_ALLOWED"
    FILE_UPLOAD_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED" 
    FILE_TYPE="Uploaded file content type:"
    FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS"
    FILE_PROCESSING_FAILED = "FILE_PROCESSING_FAILED"
    FILE_PROCESSING_SUCCESS = "FILE_PROCESSING_SUCCESS"
    NO_FILES_TO_PROCESS = "NO_FILES_TO_PROCESS"

